      - name: Build and push image
        run: |
          IMAGE=ghcr.io/${{ github.repository_owner }}/simple-webapp:latest
          docker build -t $IMAGE .
          docker push $IMAGE
          echo "image=$IMAGE" >> $GITHUB_ENV

      - name: Get image digest
        id: image_digest
        run: |
          IMAGE=ghcr.io/${{ github.repository_owner }}/simple-webapp:latest
          DIGEST=$(docker inspect --format='{{index .RepoDigests 0}}' $IMAGE | cut -d@ -f2)
          echo "digest=$DIGEST" >> $GITHUB_OUTPUT

      - name: Attest container image
        uses: actions/attest-build-provenance@v1
        with:
          subject-digest: "sha256:${{ steps.image_digest.outputs.digest }}"


